### ISSUE TITLE
cockpit-tasks: image-prune fails

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpituous#486]
Seen in cockpit-tasks container logs:
```
May 13 06:28:24 ci-srv-01 docker[30279]: + for region in eu-central-1 us-east-1
May 13 06:28:24 ci-srv-01 docker[30279]: + ./image-prune --s3 https://cockpit-images.us-east-1.linodeobjects.com/
May 13 06:28:25 ci-srv-01 docker[30279]: Traceback (most recent call last):
May 13 06:28:25 ci-srv-01 docker[30279]: File "/work/bots/./image-prune", line 232, in <module>
May 13 06:28:25 ci-srv-01 docker[30279]: main()
May 13 06:28:25 ci-srv-01 docker[30279]: File "/work/bots/./image-prune", line 223, in main
May 13 06:28:25 ci-srv-01 docker[30279]: collection.prune(keepers,
May 13 06:28:25 ci-srv-01 docker[30279]: File "/work/bots/./image-prune", line 123, in prune
May 13 06:28:25 ci-srv-01 docker[30279]: for mtime, image in sorted(self.list_files()):
May 13 06:28:25 ci-srv-01 docker[30279]: File "/work/bots/./image-prune", line 169, in list_files
May 13 06:28:25 ci-srv-01 docker[30279]: result = s3.list_bucket(self.url)
May 13 06:28:25 ci-srv-01 docker[30279]: File "/work/bots/lib/s3.py", line 112, in list_bucket
May 13 06:28:25 ci-srv-01 docker[30279]: with urlopen(url) as response:
May 13 06:28:25 ci-srv-01 docker[30279]: File "/work/bots/lib/s3.py", line 107, in urlopen
May 13 06:28:25 ci-srv-01 docker[30279]: return urllib.request.urlopen(request)
May 13 06:28:25 ci-srv-01 docker[30279]: File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
May 13 06:28:25 ci-srv-01 docker[30279]: return opener.open(url, data, timeout)
May 13 06:28:25 ci-srv-01 docker[30279]: File "/usr/lib64/python3.10/urllib/request.py", line 525, in open
May 13 06:28:25 ci-srv-01 docker[30279]: response = meth(req, response)
May 13 06:28:25 ci-srv-01 docker[30279]: File "/usr/lib64/python3.10/urllib/request.py", line 634, in http_response
May 13 06:28:25 ci-srv-01 docker[30279]: response = self.parent.error(
May 13 06:28:25 ci-srv-01 docker[30279]: File "/usr/lib64/python3.10/urllib/request.py", line 563, in error
May 13 06:28:25 ci-srv-01 docker[30279]: return self._call_chain(*args)
May 13 06:28:25 ci-srv-01 docker[30279]: File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
May 13 06:28:25 ci-srv-01 docker[30279]: result = func(*args)
May 13 06:28:25 ci-srv-01 docker[30279]: File "/usr/lib64/python3.10/urllib/request.py", line 643, in http_error_default
May 13 06:28:25 ci-srv-01 docker[30279]: raise HTTPError(req.full_url, code, msg, hdrs, fp)
May 13 06:28:25 ci-srv-01 docker[30279]: urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Presumably this has happened since https://github.com/cockpit-project/bots/pull/3365 . The tokens may not be privileged enough to list buckets?

We can probably drop the image-prune call from cockpit-tasks, but it most likely affects image refreshes as well.

**Comment by allisonkarlitskaya** [comment]
I don't think anything relevant changed here... and the same call to `image-prune`, with the same tokens, is presumably working from `image-create`...

**Comment by martinpitt** [comment]
I checked the other boxes. This was still fallout from the wrong clock, see #485.
