### ISSUE TITLE
rhos-01 machines often fail to boot VMs

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpituous#506]
Examples: [one](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17574-20220719-180222-d8001d94-fedora-coreos/log.html), [two](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17574-20220719-180221-d8001d94-rhel-9-1/log.html), [three](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17575-20220720-001339-9fb7642c-rhel-8-7/log.html)

```
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1428, in setUp
    machine.wait_boot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 130, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine fedora-coreos-127.0.0.2-2701 via ssh: 127.0.0.2:2701
```

In the first example, there are succeeding tests after that wave of failures which boot a new VM and succeed. Also, this tends to happen to tests which spawn a lot of VMs (check-multi-machine), although not exclusively.

So at first sight this smells like running out of memory in the bots.

**Comment by martinpitt** [comment]
There is nothing in dmesg or the pod logs. and we don't keep the libvirt logs; the latter would be interesting.

We overcommit memory on these tasks containers: `--memory=24g --tmpfs /tmp:size=14g --shm-size=1024m`, but the VMs only have 32 GB of RAM. The VM failure could either be the --memory or failing to create a big enough overlay in /tmp/. Our e2e bots have worked well for a long time with these parameters, so I figure 24g of RAM is generally enough.

I commented out `TMPVOL=` in tasks/install-service and rolled this out with

    ansible -i inventory -m include_role -e instances=1 -a name=tasks-systemd openstack_tasks

Let's see how much slower the tests actually are without the overlay on a tmpfs, and whether they are more robust now.

**Comment by martinpitt** [comment]
@jelly , @marusak , @mvollmer , @skobyda : FYI. If you see test runs which fail with that "unable to reach machine" symptom, please yell at me and link them here. Thank you!

**Comment by martinpitt** [comment]
I am currently [catching it in the act](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17575-20220720-044816-9fb7642c-rhel-8-7/log.html#145), even *without* a /tmp tmpfs:

Memory is fine:
```
$ free -t -h
               total        used        free      shared  buff/cache   available
Mem:            31Gi       2.5Gi        10Gi       2.0Mi        18Gi        28Gi
Swap:          8.0Gi       6.0Mi       8.0Gi
Total:          39Gi       2.5Gi        18Gi
```
Unfortunately `tail -f .cache/libvirt/qemu/log/*` does not show me any error message either.

I can run `./vm-run rhel-8-7` and it indeed hangs for some 30 seconds first, until it finally boots.

So it's not the memory, and I reverted the change above -- moving overlays to real disk isn't going to help the boot speed.

So what certainly would help here is to not schedule all the check-multi-machines tests at the same time, but spread out that "many VMs" surge.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/17577 seems to address this in a bearable way, so closing this now. I'll reopen if we still run into similar issues.
