### ISSUE TITLE
image-prune fails on minio s3 store

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpituous#563]
Seen in e.g. https://github.com/cockpit-project/bots/issues/5539 :
```
Pruning debian-testing-0da420269dbb3233e29e5d46457ba578c62661d1998da2ea6b76724c3d892fc3.qcow2
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/image-prune", line 231, in <module>
    main()
  File "/work/bots/make-checkout-workdir/image-prune", line 222, in main
    collection.prune(keepers,
  File "/work/bots/make-checkout-workdir/image-prune", line 139, in prune
    self.delete_file(image)
  File "/work/bots/make-checkout-workdir/image-prune", line 180, in delete_file
    with s3.urlopen(self.url._replace(path='/' + filename), method='DELETE'):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/lib/s3.py", line 119, in urlopen
    return urllib.request.urlopen(request, context=host_ssl_context(url.netloc))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/image-upload", line 113, in <module>
    main()
  File "/work/bots/make-checkout-workdir/image-upload", line 106, in main
    success |= upload(store, source, public, prune=args.prune_s3)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/image-upload", line 56, in upload
    subprocess.check_call([f'{BOTS_DIR}/image-prune', '--s3', store])
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/work/bots/make-checkout-workdir/image-prune', '--s3', 'http://10.0.190.233/images/']' returned non-zero exit status 1.
```

This is perfectly reproducible on rhos-01-1 with
```
./image-prune --s3 http://10.0.190.233/images/
```

This has happened for a while. So far I thought there was a new minio container and that the format changed, but that's not the case right now. My current theory is that this just always happens -- but there isn't anything to prune for the first two weeks or so, and then I removed the s3 volume and restarted the container.

Let's try to reproduce this in a local setup.

**Comment by martinpitt** [comment]
Reproducer with `tasks/run-local.sh`:

```diff
--- tasks/run-local.sh
+++ tasks/run-local.sh
@@ -226,7 +226,17 @@ test_image() {
         cd bots
         ./image-download --store '$S3_URL_POD'/images/ testimage
         grep -q "^world" /cache/images/testimage-*.qcow2
+        rm --verbose /cache/images/testimage*
         '
+
+    # validate image pruning on s3
+    podman exec -i cockpituous-tasks sh -euxc '
+      cd bots
+      rm images/testimage
+      ./image-prune --s3 '$S3_URL_POD'/images/ --force --checkout-only
+      # S3 store removed it
+      python3 -m lib.s3 ls '$S3_URL_POD'/images/ | ! grep "testimage"
+    '
 }
 
 test_pr() {
```

**Comment by martinpitt** [comment]
I went into rhos-01-1, and ran
```
cd bots
git checkout origin/fix-prune
./image-prune --force -c --s3 https://cockpit-images.eu-central-1.linodeobjects.com/
```
This works, so the fix doesn't break our public stores.
