### ISSUE TITLE
amqp/webhook startup race

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpituous#635]
Starting the AMQP and webhook container in parallel very often runs into webhook not yet being able to connect to the AMPQ server, and thus getting trapped in a crash loop until it wins the race.

This happens when deploying `oc create -f tasks/cockpit-tasks-webhook.yaml` to OpenShift.

Yesterday I did a quick hack in commit 169b53bac1998ed59997e2c27cd50baf92502d91 to delay the webhook startup. I already tried to fix that in commit 06c2717be744b9281f76934b524c66b73421a40f two years ago, but yesterday it happened again. I was distracted by a lot of other fires, so I didn't capture the precise error. Let's fix this properly.

**Comment by martinpitt** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/webhook", line 194, in <module>
    scan_tasks()
    ~~~~~~~~~~^^
  File "/usr/local/bin/webhook", line 89, in scan_tasks
    with distributed_queue(AMQP_SERVER):
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/local/bin/webhook", line 66, in distributed_queue
    connection = pika.BlockingConnection(pika.ConnectionParameters(
        host=host,
        port=int(port),
        ssl_options=pika.SSLOptions(context, server_hostname=host),
        credentials=pika.credentials.ExternalCredentials()))
  File "/usr/lib/python3.13/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/usr/lib/python3.13/site-packages/pika/adapters/utils/io_services_utils.py", line 636, in _do_ssl_handshake
    self._sock.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1020)
```

So that makes sense, 06c2717be744b928 only checks for AMQPError.
